### ISSUE TITLE
no released version compatible with SSP 2.1

### ISSUE THREAD

**Issue by restena-sw** [simplesamlphp/simplesamlphp-module-authcrypt#1]
The latest SSP requires simplesamlphp/assert version ^1.0.0, but the latest release v1.0.4 of this module here requires ~0.8.0.

I see that the release-1.0 branch already has the dependency fixed. It may be the time to tag a version with the updated dependency for ease of deployment.

**Comment by tvdijen** [comment]
Consider it done!

**Comment by tvdijen** [comment]
Care to try v1.1.0? Let me know if it works

**Comment by tvdijen** [comment]
May I ask how you're using this package? The reason I'm asking is that we have a 9y unmanaged dependency on https://github.com/whitehat101/apr1-md5

**Comment by restena-sw** [comment]
I use it with bcrypt hashes, certainly not anything based on MD5.

**Comment by restena-sw** [comment]
And yes, v1.1.0 rolls out on SSP 2.1.1 without issues. Thanks!
